# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCloseads():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_closeads(self):
    self.driver.get("https://www.latimes.com/")
    self.driver.set_window_size(1439, 680)
    self.driver.find_element(By.CSS_SELECTOR, ".xs-5\\3Ah-6").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(5)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.NAME, "q").click()
    self.driver.find_element(By.NAME, "q").send_keys("Iran")
    self.driver.find_element(By.CSS_SELECTOR, ".h-6\\.25").click()
    self.driver.find_element(By.NAME, "s").click()
    dropdown = self.driver.find_element(By.NAME, "s")
    dropdown.find_element(By.XPATH, "//option[. = 'Newest']").click()
    self.driver.find_element(By.NAME, "f0").click()
    element = self.driver.find_element(By.NAME, "f0")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".search-filter:nth-child(1) li:nth-child(2) .checkbox-input-element:nth-child(1)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".search-filter:nth-child(1) li:nth-child(2) .checkbox-input-element:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.NAME, "f0")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".search-filter:nth-child(1) li:nth-child(4) .checkbox-input-element:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, "a > .chevron-icon").click()
  
